name: cs436_project
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      express:
        condition: service_started
        required: true
      socketio:
        condition: service_started
        required: true
    environment:
      CLIENT_PORT: "80"
      EXPRESS_PORT: "8000"
      MONGODB_PORT: "27017"
      SOCKET_IO_PORT: "8001"
      VITE_PUBLIC_SERVER_URL: http://express:8000
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
    volumes:
      - type: bind
        source: ./client/public
        target: /app/public
        bind:
          create_host_path: true
      - type: bind
        source: ./client/src
        target: /app/src
        bind:
          create_host_path: true
  express:
    build:
      context: ./express
      dockerfile: Dockerfile
    depends_on:
      mongo:
        condition: service_started
        required: true
    environment:
      CLIENT_PORT: "80"
      EXPRESS_PORT: "8000"
      MONGODB_PORT: "27017"
      SECRET: drakeisapedofile
      SOCKET_IO_PORT: "8001"
      URL: mongodb://mongo:27017
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8000
        published: "8000"
        protocol: tcp
  mongo:
    image: mongo:latest
    networks:
      default: null
    ports:
      - mode: ingress
        target: 27017
        published: "27017"
        protocol: tcp
    restart: always
  socketio:
    build:
      context: ./socketio
      dockerfile: Dockerfile
    environment:
      CLIENT_PORT: "80"
      EXPRESS_PORT: "8000"
      FRONTEND_BASE_URL: localhost
      MONGODB_PORT: "27017"
      SOCKET_IO_PORT: "8001"
    networks:
      default: null
    ports:
      - mode: ingress
        target: 8001
        published: "8001"
        protocol: tcp
networks:
  default:
    name: cs436_project_default
