apiVersion: v1
data:
  App.jsx: |
    import Login from './pages/Login';
    import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
    import Register from './pages/Register';
    import Home from './pages/Home';
    import Start from './components/Start';

    function App() {
      return (
        <div className="bg-[#F8F4EA]">
          <Router>
            <Routes>
              <Route exact path="/login" element={<Login />} />
              <Route exact path="/register" element={<Register />} />
              <Route exact path="/chats" element={<Home />} />
              <Route exact path="/" element={<Start />} />
            </Routes>
          </Router>
        </div>
      );
    }

    export default App;
  index.tsx: |
    import { createRoot } from 'react-dom/client'
    import 'tailwindcss/tailwind.css'
    import App from './App'

    import { Provider } from 'react-redux';
    import store from './store';
    import { ToastContainer } from 'react-toastify';
    import 'react-toastify/dist/ReactToastify.css';

    const container = document.getElementById('root') as HTMLDivElement
    const root = createRoot(container)

    root.render(
        <Provider store={store}>
          <App />
          <ToastContainer position="top-right" />
        </Provider>
    )
  store.js: |
    import { configureStore } from "@reduxjs/toolkit";
    import activeUserSlice from "./redux/activeUserSlice";
    import chatsSlice from "./redux/chatsSlice";
    import profileSlice from "./redux/profileSlice";
    import searchSlice from "./redux/searchSlice";
    const store = configureStore({
      reducer: {
        activeUser: activeUserSlice,
        profile: profileSlice,
        search: searchSlice,
        chats: chatsSlice,
      },
    });
    export default store;
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: client
  name: client-cm1
