version: "3"

services:
    mongo:
      image: arm64v8/mongo:latest
      platform: linux/arm64/v8
      container_name: mongo
      restart: always
      ports:
        - "${MONGODB_PORT}:${MONGODB_PORT}"
    
