name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set k8s directory based on REPLICA_MODE
      id: set-dirr
      run: |
        if [ "$REPLICA_MODE" == "0" ]; then
          echo "K8S_DIR=./k8s/low" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "1" ]; then
          echo "K8S_DIR=./k8s/medium" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "2" ]; then
          echo "K8S_DIR=./k8s/high" >> $GITHUB_ENV
        else
          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
          exit 1
        fi
      env:
        REPLICA_MODE: ${{ vars.REPLICA_MODE }}  # Access repository variable

    - name: Print K8S_DIR
      run: echo "K8S_DIR is $K8S_DIR"
      env:
        K8S_DIR: ${{ env.K8S_DIR }}

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.AUTH_FOR_CICD }}
      run: echo "${GCP_SERVICE_ACCOUNT_KEY}" > /tmp/service-account-key.json

    - name: Configure Docker for gcloud
      run: |
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        gcloud config set project pristine-clone-339910
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Build and deploy terraform image
      run: pwd && ls

    - name: Set permissions for .env.example files
      run: |
        chmod +x .env.example
        chmod +x socketio/.env.example
        chmod +x client/.env.example
        chmod +x express/.env.example

    - name: Move/Rename .env.example files
      run: |
        mv .env.example .env
        mv socketio/.env.example socketio/.env
        mv client/.env.example client/.env
        mv express/.env.example express/.env
        
    - name: Update images
      run: ./update_images.sh

    - name: Change GCP Key (OKTAY)
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.AUTH_FOR_CICD_OKTAY }}
      run: |
        rm -rf /tmp/service-account-key.json
        echo "${GCP_SERVICE_ACCOUNT_KEY}" > /tmp/service-account-key.json

    - name: GCP auth (OKTAY)
      run: |
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        gcloud config set project linen-setting-417209\

    - name: get clusters (OKTAY)
      run: gcloud container clusters get-credentials cluster-1 --zone us-central1-c --project linen-setting-417209
    
    - name: install gke auth plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Set k8s directory based on REPLICA_MODE
      id: set-dir
      run: |
        if [ "$REPLICA_MODE" == "0" ]; then
          echo "K8S_DIR=./k8s/low" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "1" ]; then
          echo "K8S_DIR=./k8s/medium" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "2" ]; then
          echo "K8S_DIR=./k8s/high" >> $GITHUB_ENV
        else
          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
          exit 1
        fi
      env:
        REPLICA_MODE: ${{ vars.REPLICA_MODE }}  # Access repository variable

    - name: Run Deployment Script
      run: |
        kubectl delete -f $K8S_DIR --ignore-not-found=true
        kubectl delete service nginx1 || true
        kubectl apply -f $K8S_DIR
        kubectl expose deployment nginx --name=nginx1 --type=LoadBalancer --port 80 --target-port 80
      env:
        K8S_DIR: ${{ env.K8S_DIR }}
        REPLICA_MODE: ${{ vars.REPLICA_MODE }}
