name: Build and Push Docker Image

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set k8s directory based on REPLICA_MODE
      id: set-dir2
      run: |
        if [ "$REPLICA_MODE" == "0" ]; then
          echo 0
        elif [ "$REPLICA_MODE" == "1" ]; then
          echo 1
        elif [ "$REPLICA_MODE" == "2" ]; then
          echo 2
        else
          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
          exit 1
        fi
      env:
        REPLICA_MODE: ${{ vars.REPLICA_MODE }}  # Access repository variable

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'

    - name: Authenticate to Google Cloud
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.AUTH_FOR_CICD }}
      run: echo "${GCP_SERVICE_ACCOUNT_KEY}" > /tmp/service-account-key.json

    - name: Configure Docker for gcloud
      run: |
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        gcloud config set project pristine-clone-339910
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: where am i
      run: pwd && ls

    - name: Set permissions for .env.example files
      run: |
        chmod +x .env.example
        chmod +x socketio/.env.example
        chmod +x client/.env.example
        chmod +x express/.env.example

    - name: Move/Rename .env.example files
      run: |
        mv .env.example .env
        mv socketio/.env.example socketio/.env
        mv client/.env.example client/.env
        mv express/.env.example express/.env
        
    - name: Update images
      run: ./update_images.sh

    - name: Change GCP Key (baris)
      env:
        GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.AUTH_FOR_CICD_BARIS }}
      run: |
        rm -rf /tmp/service-account-key.json
        echo "${GCP_SERVICE_ACCOUNT_KEY}" > /tmp/service-account-key.json

    - name: GCP auth (baris)
      run: |
        gcloud auth activate-service-account --key-file=/tmp/service-account-key.json
        gcloud config set project cloudprojtrial\

    - name: get clusters (baris)
      run: gcloud container clusters get-credentials cluster-new --zone us-central1-c --project cloudprojtrial
    
    - name: install gke auth plugin
      run: gcloud components install gke-gcloud-auth-plugin

    - name: Set k8s directory based on REPLICA_MODE
      id: set-dir
      run: |
        if [ "$REPLICA_MODE" == "0" ]; then
          echo "K8S_DIR=k8s/low" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "1" ]; then
          echo "K8S_DIR=k8s/medium" >> $GITHUB_ENV
        elif [ "$REPLICA_MODE" == "2" ]; then
          echo "K8S_DIR=k8s/high" >> $GITHUB_ENV
        else
          echo "Invalid REPLICA_MODE value. Must be 0, 1, or 2."
          exit 1
        fi
      env:
        REPLICA_MODE: ${{ vars.REPLICA_MODE }}  # Access repository variable
      
    - name: run sh
      run: ./create_services_cicd.sh
